### ISSUE TITLE
Variable knob height based on length of content

### ISSUE THREAD

**Issue by julianlam** [julianlam/Scrollable#7]
Thierry Philippe suggests:

> Would it be possible to change knob height according to div content (maybe using getScrollSize and a little formula like: divheight.y / divscroll.y \* 100).

**Comment by afoeder** [comment]
funny; I also wished that. Where I got stuck is the correct formula, because it's not as simple as it looks at the first insight.

We so far need definately a minimum height that doesn't exceed in order to keep the knob "touchable". Then, kind of an exponential ratio is required, it's kind of `(scrollheight - visibleheight) / visibleheight` or such, but as said: I'm not sure.

Feel free to add comments and thoughts.

**Comment by afoeder** [comment]
I found this one so far: https://github.com/syntacticx/livepipe-ui/blob/master/src/scrollbar.js#L113 Will experiment if that fits my ideas. :)
